services:

  mysql:
    image: mysql:8
    container_name: disasteralert-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: disasteralert
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: disasteralert-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: disasteralert-nginx
    restart: always
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  prometheus:
    image: prom/prometheus
    container_name: disasteralert-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - app



  grafana:
    image: grafana/grafana
    container_name: disasteralert-grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus

volumes:
  mysql_data:

