services:

  mysql:
    image: mysql:8

    container_name: disasteralert-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: disasteralert

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .

    container_name: disasteralert-app

    restart: always

    depends_on:
      - mysql

    ports:
      - "8000:8000"

volumes:
  mysql_data: